---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  chef_omnibus_root: C:/opscode/chefdk/

platforms:
  - name: windows-8.1

suites:
  - name: default
    run_list:
      - recipe[winbox-local::default]
    attributes: { winbox-local: { source_destination: "c:/lb/source" } }